#!/bin/sh

NETWORK=$1

# Run the bitcoind process
bitcoind --datadir=/home/ubuntu/.bitcoin >> runLogBitcoin.log 2>&1 &

# Run lightning process
/home/ubuntu/lightning/lightningd/lightningdi --log-level=debug --daemon >> runLogLightning.log 2>&1 &

# Run the mining process if regtest network
if test "$NETWORK" = "regtest"
then
	while true; do bitcoin-cli generate 1; sleep 300; done
fi
